name       : perl-devel-cycle
version    : 1.12
release    : 2
source     :
    - https://cpan.metacpan.org/authors/id/L/LD/LDS/Devel-Cycle-1.12.tar.gz : fd3365c4d898b2b2bddbb78a46d507a18cca8490a290199547dab7f1e7390bc2
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Devel::Cycle - Find memory cycles in objects
description: |
    Devel::Cycle - Find memory cycles in objects
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
